{
 "title": "Syncthing / Overview",
 "description": "A dashboard that monitors Syncthing. The dashboards were generated using syncthing-mixin. https://github.com/adinhodovic/syncthing-mixin. Open issues and create feature requests in the repository.",
 "tags": [
  "syncthing",
  "syncthing-mixin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(syncthing_events_total{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(syncthing_events_total{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "folder",
    "label": "Folder",
    "query": "label_values(syncthing_model_folder_summary{cluster=\"$cluster\", job=~\"$job\"}, folder)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(syncthing_protocol_sent_bytes_total{cluster=\"$cluster\", job=~\"$job\"}, device)"
   },
   {
    "name": "file_system",
    "label": "File System",
    "query": "label_values(syncthing_fs_operations_total{cluster=\"$cluster\", job=~\"$job\"}, root)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Folders",
   "type": "stat",
   "description": "The total number of folders being synchronized by Syncthing.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  syncthing_model_folder_state{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  }\n) by (folder)\n"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "description": "The total number of devices connected to Syncthing.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  count(\n    syncthing_protocol_recv_bytes_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }\n  ) by (device)\n)\n"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "description": "The rate of events occurring in Syncthing, measured in events per second.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_events_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Filesystem Operations",
   "type": "stat",
   "description": "The rate of filesystem operations performed by Syncthing, measured in operations per second.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_fs_operations_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Folders by State",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "count(\n  syncthing_model_folder_state{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  } == 0\n)\n",
     "legendFormat": "Synced"
    },
    {
     "expr": "count(\n  syncthing_model_folder_state{\n    cluster=\"$cluster\",\njob=~\"$job\"\n\n  } > 0\n)\n",
     "legendFormat": "Unsynced"
    }
   ]
  },
  {
   "title": "Events by Type [1h]",
   "type": "piechart",
   "description": "The distribution of events in Syncthing, categorized by event type over the last hour.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_events_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (event)\n> 0\n",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Folder Total Bytes",
   "type": "timeseries",
   "description": "The total number of bytes in each folder being synchronized by Syncthing.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    scope=\"global\",\n    type=\"bytes\"\n  }\n)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Folder Total Directories",
   "type": "timeseries",
   "description": "The total number of directories in each folder being synchronized by Syncthing.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    scope=\"global\",\n    type=\"directories\"\n  }\n)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Folder Total Files",
   "type": "timeseries",
   "description": "The total number of files in each folder being synchronized by Syncthing.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    scope=\"global\",\n    type=\"files\"\n  }\n)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Folder Total Deleted Items",
   "type": "timeseries",
   "description": "The total number of deleted items in each folder being synchronized by Syncthing.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\n    scope=\"global\",\n    type=\"deleted\"\n  }\n)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Events Created Rate",
   "type": "timeseries",
   "description": "The rate of created events in Syncthing, categorized by event type and measured in events per second.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_events_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\n      state=\"created\"\n    }[$__rate_interval]\n  )\n) by (event)\n",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Events Delivered Rate",
   "type": "timeseries",
   "description": "The rate of delivered events in Syncthing, categorized by event type and measured in events per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_events_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\n      state=\"delivered\"\n    }[$__rate_interval]\n  )\n) by (event)\n",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Events Dropped Rate",
   "type": "timeseries",
   "description": "The rate of Dropped events in Syncthing, categorized by event type and measured in events per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_events_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\n      state=\"dropped\"\n    }[$__rate_interval]\n  )\n) by (event)\n",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  { "title": "Folders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Folder State",
   "type": "timeseries",
   "description": "The current state of each folder being synchronized by Syncthing, categorized by state type.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_state{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n\n  }\n) by (folder, state)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Needed Bytes by Folder",
   "type": "timeseries",
   "description": "The number of bytes needed to be synchronized in each folder by Syncthing, categorized by folder.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n,\n    scope=\"need\",\n    type=\"bytes\"\n  }\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Total Bytes by Folder",
   "type": "timeseries",
   "description": "The total number of bytes in each folder being synchronized by Syncthing, categorized by folder.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n,\n    scope=\"global\",\n    type=\"bytes\"\n  }\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Total Directories by Folder",
   "type": "timeseries",
   "description": "The total number of directories in each folder being synchronized by Syncthing, categorized by folder.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n,\n    scope=\"global\",\n    type=\"directories\"\n  }\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Total Files by Folder",
   "type": "timeseries",
   "description": "The total number of files in each folder being synchronized by Syncthing, categorized by folder.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n,\n    scope=\"global\",\n    type=\"files\"\n  }\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Total Deleted Items by Folder",
   "type": "timeseries",
   "description": "The total number of deleted items in each folder being synchronized by Syncthing, categorized by folder.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  syncthing_model_folder_summary{\n    cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n,\n    scope=\"global\",\n    type=\"deleted\"\n  }\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Folder Pulls Rate",
   "type": "timeseries",
   "description": "The rate of pull operations for each folder, measured in pulls per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_model_folder_pulls_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n\n    }[$__rate_interval]\n  )\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Folder Scans Rate",
   "type": "timeseries",
   "description": "The rate of scan operations for each folder, measured in scans per second.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_model_folder_scans_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n\n    }[$__rate_interval]\n  )\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Scanner Hashed Bytes Rate",
   "type": "timeseries",
   "description": "The rate of bytes hashed during scans by Syncthing, measured in bytes per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    syncthing_scanner_hashed_bytes_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n\n    }[$__rate_interval]\n  )\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  {
   "title": "Scanner Scanned Items Rate",
   "type": "timeseries",
   "description": "The rate of items scanned by Syncthing, measured in items per second.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_scanner_scanned_items_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nfolder=~\"$folder\"\n\n    }[$__rate_interval]\n  )\n) by (folder)\n",
     "legendFormat": "{{ folder }}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Filesystem Operations Rate",
   "type": "timeseries",
   "description": "The rate of filesystem operations performed by Syncthing, categorized by operation type and root directory, measured in operations per second.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_fs_operations_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nroot=~\"$file_system\"\n\n    }[$__rate_interval]\n  )\n) by (root, operation)\n> 0\n",
     "legendFormat": "{{ root }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Filesystem Operations Bytes Rate",
   "type": "timeseries",
   "description": "The rate of bytes processed during filesystem operations by Syncthing, categorized by operation type and root directory, measured in bytes per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_fs_operation_bytes_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nroot=~\"$file_system\"\n\n    }[$__rate_interval]\n  )\n) by (root, operation)\n> 0\n",
     "legendFormat": "{{ root }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Filesystem Operations Seconds Rate",
   "type": "timeseries",
   "description": "The rate of time spent on filesystem operations by Syncthing, categorized by operation type and root directory, measured in seconds per second.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    syncthing_fs_operation_seconds_total{\n      cluster=\"$cluster\",\njob=~\"$job\"\n,\nroot=~\"$file_system\"\n\n    }[$__rate_interval]\n  )\n) by (root, operation)\n> 0\n",
     "legendFormat": "{{ root }} - {{ operation }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Network Sent Bytes Rate",
   "type": "timeseries",
   "description": "The rate of bytes sent over the network by Syncthing, measured in bytes per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    increase(\n      syncthing_protocol_sent_bytes_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n,\ndevice=~\"$device\"\n\n      }[$__rate_interval]\n    ),\n    \"device\", \"$1\", \"device\", \"^(.{1,15}).*\"\n  )\n) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Sent Messages Rate",
   "type": "timeseries",
   "description": "The rate of messages sent over the network by Syncthing, measured in messages per second.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    increase(\n      syncthing_protocol_sent_messages_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n,\ndevice=~\"$device\"\n\n      }[$__rate_interval]\n    ),\n    \"device\", \"$1\", \"device\", \"^(.{1,15}).*\"\n  )\n) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Received Bytes Rate",
   "type": "timeseries",
   "description": "The rate of bytes received over the network by Syncthing, measured in bytes per second.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    increase(\n      syncthing_protocol_recv_bytes_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n,\ndevice=~\"$device\"\n\n      }[$__rate_interval]\n    ),\n    \"device\", \"$1\", \"device\", \"^(.{1,15}).*\"\n  )\n) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Network Received Messages Rate",
   "type": "timeseries",
   "description": "The rate of messages received over the network by Syncthing, measured in messages per second.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    increase(\n      syncthing_protocol_recv_messages_total{\n        cluster=\"$cluster\",\njob=~\"$job\"\n,\ndevice=~\"$device\"\n\n      }[$__rate_interval]\n    ),\n    \"device\", \"$1\", \"device\", \"^(.{1,15}).*\"\n  )\n) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}